#!/bin/sh
### BEGIN INIT INFO
# Provides:         xvfb
# Required-Start:
# Required-Stop:
# Default-Start:
# Default-Stop:
# Short-Description: execute the xvfb command.
# Description:
### END INIT INFO

# http://web-dev.hatenablog.com/entry/linux/ubuntu/script-xvfb

XVFB=/usr/bin/Xvfb
ARGS=":1 -screen 0 1024x764x24"
PIDFILE=/var/run/xvfb.pid

start() {
  echo -n "Starting XVFB: "
  /sbin/start-stop-daemon --start --quiet --pidfile $PIDFILE --make-pidfile --background --exec $XVFB -- $ARGS
  echo "."
}

stop() {
  echo -n "Stopping XVFB: "
  /sbin/start-stop-daemon --stop --quiet --pidfile $PIDFILE
  echo "."
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
  esac

  exit 0

